export default {
  HOME: 'Home',
  CAMERA: 'Camera',
  CONTACTS: 'Contacts',
  MAP: 'Map',
  REDUX: 'Redux',
  FORGET_PASSWORD: 'Forget Password',
  SIGN_UP: 'Sign UP',
  SIGN_IN: 'Sign IN',
  LOGIN: 'Login',
  EMAIL: 'Email',
  PASSWORD: 'PASSWORD0',
  ALREADY_EXIST: 'Already Have an Account',
  SEND_RESET_LINK: 'Send Reset Link',
  PRESS_ME: 'Press Me',
  LOG_OUT: 'Log Out',
  USERNAME: 'Username',
  FIRST_NAME: 'First Name',
  PHONE_NUMBER: 'Phone Number',
  CONTACT_CREATE: 'Contact Create',
  CAPTURE: 'Capture',
  URDU: 'اردو',
  CREATE_ACCOUNT: 'Create Account',
  RESET_PASSWORD: 'Reset Password',
  MAIN_MENU: 'Main Menu',
  INTERCEPTOR: 'Interceptor',
  DIALER: 'Dialer & Cam',
};
