//URDU DICTONARY
export default {
  HOME: 'گھر',
  CAMERA: 'کیمرہ',
  CONTACTS: 'رابطے',
  MAP: 'نقشہ',
  REDUX: 'رڈیکس',
  FORGET_PASSWORD: 'پاس ورڈ بھول جائیں',
  SIGN_UP: 'سائن اپ',
  SIGN_IN: 'سائن ان',
  LOGIN: 'لاگ ان',
  EMAIL: 'ای میل',
  PASSWORD: 'پاس ورڈ',
  ALREADY_EXIST: 'پہلے سے ہی ایک اکاؤنٹ ہے',
  SEND_RESET_LINK: 'ری سیٹ لنک بھیجیں',
  PRESS_ME: 'پوسٹس حاصل کریں',
  LOG_OUT: 'لاگ آؤٹ',
  USERNAME: 'صارف نام',
  FIRST_NAME: 'پہلا نام',
  PHONE_NUMBER: 'فون نمبر',
  CONTACT_CREATE: 'رابطہ بنائیں',
  CAPTURE: 'کیپچر',
  URDU: 'اردو',
  CREATE_ACCOUNT: 'اکاؤنٹ بنائیں',
  RESET_PASSWORD: 'پاس ورڈ دوبارہ ترتیب دیں',
  MAIN_MENU: 'مین مینو',
  INTERCEPTOR: 'انٹرسیپٹر',
  DIALER: 'ڈائلرڈائلر اور کیم',
  CRUD: 'CRUD',
  CALL: 'کال',
  PASSWORD_WARNING: 'پاس ورڈ 7 حروف سے بڑا ہونا چاہیے۔',
  EMAIL_WARNING: 'ای میل درست نہیں ہے۔',
};
